### ISSUE TITLE
Admin delete duplicate model fails when there's an existing aircraft (or at least one where it's duplicated between both models)

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#1068]
Request = https://myflightbook.com/logbook/Admin/Admin.aspx?t=admModels
Language=en-US, en-ZA;q=0.9, en;q=0.8, de;q=0.7, no;q=0.6, da;q=0.5, fr;q=0.4, cs;q=0.3
By: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 24.16.27.179 24.16.27.179

Referrer requested: https://myflightbook.com/logbook/Admin/Admin.aspx?t=admModels
Last page requested by user = https:myflightbook.com/logbook/Admin/Admin.aspx?t=admModels

Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
Target site
Boolean HandleError(System.Exception)

Stack trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.admin_admin_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> MyFlightbook.MyFlightbookException: Exception DoNonQuery:
Code = -2147467259
Cannot delete or update a parent row: a foreign key constraint fails (`logbook`.`aircraft`, CONSTRAINT `fkaircraftmodel` FOREIGN KEY (`idmodel`) REFERENCES `models` (`idmodel`) ON UPDATE NO ACTION) DELETE FROM models WHERE idmodel=?idOldModel ---> MySql.Data.MySqlClient.MySqlException: Cannot delete or update a parent row: a foreign key constraint fails (`logbook`.`aircraft`, CONSTRAINT `fkaircraftmodel` FOREIGN KEY (`idmodel`) REFERENCES `models` (`idmodel`) ON UPDATE NO ACTION)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MyFlightbook.DBHelper.DoNonQuery(DBHelperCommandArgs args, Action`1 initCommand) in C:\Users\ericb\GitHub\MyFlightbookWeb\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 312
   --- End of inner exception stack trace ---
   at MyFlightbook.DBHelper.DoNonQuery(DBHelperCommandArgs args, Action`1 initCommand) in C:\Users\ericb\GitHub\MyFlightbookWeb\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 320
   at MyFlightbook.MakeModel.AdminMergeDuplicateModels(Int32 idModelToDelete, Int32 idModelToMergeInto) in C:\Users\ericb\GitHub\MyFlightbookWeb\MyFlightbook.Web\AppCode\Aircraft\Makes.cs:line 1025
   at MyFlightbook.Web.Admin.Member_Admin.btnDeleteDupeMake_Click(Object sender, EventArgs e) in C:\Users\ericb\GitHub\MyFlightbookWeb\MyFlightbook.Web\Admin\Admin.aspx.cs:line 131

**Comment by ericberman** [comment]
Here's a test scenario using A-9 (modelIDs 6294 and 8977), with N7207V - keep 6294 and kill 8977
INSERT INTO `logbook`.`aircraft` (`tailnumber`, `tailNormal`, `version`, `idmodel`, `InstanceType`, `Last100`, `LastOil`, `LastEngine`, `HasGlassUpgrade`, `HasTAAUpgrade`, `isLocked`, `Revision`) VALUES ('N7207V', 'N7207V', '0', '6294', '1', '0', '0', '0', '0', '0', '0', '0');
