### ISSUE TITLE
Crash setting preferred name for use

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#668]
Request = https://myflightbook.com/logbook/Default.aspx
User = tferris2
Language=en-us
By: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15 96.63.252.165 96.63.252.165

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.

Source
System.Web

Target site
Boolean HandleError(System.Exception)

Stack trace
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Overall Data:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Public_Home.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Default.aspx.cs:line 62
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Occured at: 09/23/2020 14:57:23 (UTC)

Moving to next exception down...

Message
Object reference not set to an instance of an object.

Source
MyFlightbook.Web

Target site
Void Page_Load(System.Object, System.EventArgs)

Stack trace
   at Public_Home.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Default.aspx.cs:line 62
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Overall Data:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Public_Home.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Default.aspx.cs:line 62
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Occured at: 09/23/2020 14:57:23 (UTC)

Moving to next exception down...

**Comment by ericberman** [comment]
I have no idea what caused this unless getuser failed, which it should not have done.
