### ISSUE TITLE
crash in setting compact view

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#669]
Request = https://myflightbook.com/logbook/Member/LogbookNew.aspx
User = dwight.dutton
Language=en-US, en;q=0.9
By: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 38.88.197.74 38.88.197.74

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.

Source
System.Web

Target site
Boolean HandleError(System.Exception)

Stack trace
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.member_logbooknew_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\logbook\be8e4906\ebaf167d\App_Web_0lfp2ivd.0.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Overall Data:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Controls_mfbLogbook.Page_Init(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbLogbook.ascx.cs:line 556
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.member_logbooknew_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\logbook\be8e4906\ebaf167d\App_Web_0lfp2ivd.0.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Occured at: 09/23/2020 20:08:47 (UTC)

Moving to next exception down...

Message
Object reference not set to an instance of an object.

Source
MyFlightbook.Web

Target site
Void Page_Init(System.Object, System.EventArgs)

Stack trace
   at Controls_mfbLogbook.Page_Init(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbLogbook.ascx.cs:line 556
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Overall Data:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Controls_mfbLogbook.Page_Init(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbLogbook.ascx.cs:line 556
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Occured at: 09/23/2020 20:08:47 (UTC)

Moving to next exception down...

**Comment by ericberman** [comment]
May be a function of the fact that the user here no longer exists (stale page?)

**Comment by ericberman** [comment]
Verified.  Dwight.dutton does not exist as a user, results in null.
