### ISSUE TITLE
Seeing this error when migrating aircraft - how?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#728]
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Overall Data:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: acSrc
   at MyFlightbook.Aircraft.AdminMigrateFlights(String szUser, Aircraft acSrc, Aircraft acTarget) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Aircraft\Aircraft.cs:line 1643
   at Member_Aircraft.btnMigrate_Click(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\Aircraft.aspx.cs:line 160

**Comment by ericberman** [comment]
I'm guessing this is two windows: delete aircraft in one window, then migrate in the other.  Test for null aircraft.
