### ISSUE TITLE
Error enumerating basicmed?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#729]
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Controls_mfbBasicMedManager.gvBasicMedEvents_RowCommand(Object sender, CommandEventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbBasicMedManager.ascx.cs:line 78
   at System.Web.UI.WebControls.GridView.OnRowCommand(GridViewCommandEventArgs e)
   at System.Web.UI.WebControls.GridView.HandleEvent(EventArgs e, Boolean causesValidation, String validationGroup)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)

**Comment by ericberman** [comment]
Linq First() is throwing an exception because the basicmed item with the specified ID isn't found. (Or, two tabs open?)

I'm guessing this is a postback error - already deleted on the first deletion.  Switch to using FirstOrDefault, which can gracefully return null.
