### ISSUE TITLE
Crash in view distance on airports page

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#837]
Looks like this happens when clicking on the link to compute distance.  Flight ID it happens on is 4038853 - ending up with null telemetry data.  I notice that there are 6 flights in flight telemetry with 0 distance - is it just a bad telemetry file?  If so, just code around this (i.e.,

Request = https://myflightbook.com/logbook/Member/Airports.aspx
User = [xxx]
Language=en-US, en;q=0.5
By: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 154.6.28.68 154.6.28.68

Referrer requested: https://myflightbook.com/logbook/Member/Airports.aspx
Last page requested by user = https:myflightbook.com/logbook/Member/Airports.aspx

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.

Source
System.Web

Target site
Boolean HandleError(System.Exception)

Stack trace
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.member_airports_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Overall Data:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> MyFlightbook.MyFlightbookException: Uncaught exception in ReadRows:
:SELECT flights.idFlight,
    flights.date,
    flights.idaircraft,
    flights.cInstrumentApproaches,
    flights.cLandings,
    flights.crosscountry,
    flights.night,
    flights.IMC,
    flights.simulatedInstrument,
    flights.dualReceived,
    flights.PIC,
    flights.totalFlightTime,
    flights.fHold,
    flights.Route,
    flights.Comments,
    flights.username,
    flights.groundSim,
    flights.fPublic,
    flights.hobbsStart,
    flights.hobbsEnd,
    IF(YEAR(flights.dtEngineStart) < 100, NULL, flights.dtEngineStart) AS dtEngineStart,
    IF(YEAR(flights.dtEngineEnd) < 100, NULL, flights.dtEngineEnd) AS dtEngineEnd,
    IF(YEAR(flights.dtFlightStart) < 100, NULL, flights.dtFlightStart) AS dtFlightStart,
    IF(YEAR(flights.dtFlightEnd) < 100, NULL, flights.dtFlightEnd) AS dtFlightEnd,
    flights.cfi,
    flights.SIC,
    flights.cNightLandings,
    flights.cFullStopLandings,
    flights.idCatClassOverride,
    flights.FlightHash,
    flights.SignatureHash,
    flights.CFIComment,
    flights.SignatureDate,
    flights.CFICertificate,
    flights.CFIExpiration,
    flights.CFIUserName,
    flights.CFIEmail,
    flights.CFIName,
    IF (flights.DigitizedSignature IS NOT NULL AND Length(DigitizedSignature) > 0, 1, 0) AS HasDigitizedSignature,
    flights.SignatureState,
    CAST(UNCOMPRESS(flights.Telemetry) AS CHAR) AS FlightData, 
    IF (coalesce(flights.Telemetry, ft.idflight) IS NULL, 0, 1) AS FlightDataLength,
    ft.distance,
    ft.flightpath,
    ft.telemetrytype,
    fp2.DateValue AS blockOut,
    CONCAT('[', GROUP_CONCAT(DISTINCT IF(fv.idFlightVideos IS NULL, '', JSON_OBJECT("ID", fv.idFlightVideos, "FlightID", fv.idFlight, "VideoReference", fv.vidRef, "Comment", fv.comment)) SEPARATOR ', '), ']') AS FlightVids,
    CONCAT('[', GROUP_CONCAT(DISTINCT IF(fdc.idprop IS NULL, '', JSON_ARRAY(fdc.idprop, fdc.idPropType, ELT(cpt.type + 1, fdc.IntValue, fdc.DecValue, IF(fdc.IntValue<>0, 'true', 'false'), fdc.DateValue, fdc.DateValue, fdc.StringValue, fdc.DecValue))) ORDER BY CONCAT(cpt.sortkey, cpt.FormatString) ASC SEPARATOR ', '), ']') AS CustomPropsJSON,
    GROUP_CONCAT(DISTINCT REPLACE(cpt.FormatString, '{0}', ELT(cpt.type + 1, fdc.IntValue, fdc.DecValue, '', fdc.DateValue, fdc.DateValue, fdc.StringValue, fdc.DecValue)) SEPARATOR ' ') AS CustomProperties,
    models.*,
    IF(models.fTAA <> 0 OR (aircraft.HasTAAUpgrade  <> 0 AND (aircraft.GlassUpgradeDate IS NULL OR flights.date >= aircraft.GlassUpgradeDate)), 1, 0) AS IsTAA,
    if (flights.idCatClassOverride = 0 OR flights.idCatClassOverride=models.idCategoryClass, 0, 1) AS IsOverridden,
    if (flights.idCatClassOverride = 0, models.idcategoryclass, flights.idCatClassOverride) AS CatClassOverride,
    TRIM(CONCAT(models.model, ', ', manufacturers.Manufacturer, ' ',  models.typename, ' ', models.modelname)) AS ModelDisplay,
    TRIM(CONCAT(manufacturers.Manufacturer, ' ', models.model)) AS ShortModelDisplay,
    IF(models.family is null OR models.family='', models.model, models.family) AS FamilyDisplay,
    IF (aircraft.Tailnumber LIKE '#%', CONCAT('(', models.model, ')'), aircraft.tailnumber) AS 'TailNumberDisplay',
    aircraft.TailNumber AS RawTailNumber,
    aircraft.InstanceType,
    CONCAT(IF(ccOver.CatClass is null, ccOrig.CatClass, ccOver.CatClass), IF(models.typename='','', CONCAT(' (', models.typename, ')'))) AS CatClassDisplay FROM flights
  INNER JOIN aircraft ON flights.idaircraft = aircraft.idaircraft
  INNER JOIN models ON aircraft.idmodel = models.idmodel
  INNER JOIN manufacturers ON manufacturers.idmanufacturer = models.idmanufacturer
  INNER JOIN categoryclass ccOrig ON (models.idCategoryClass = ccOrig.idCatClass)
  
  LEFT JOIN flighttelemetry ft ON (flights.idflight=ft.idflight)
  LEFT JOIN categoryclass ccOver ON (flights.idCatClassOverride = ccOver.idCatClass)
  LEFT JOIN FlightProperties fdc ON flights.idFlight=fdc.idFlight
  LEFT JOIN custompropertytypes cpt ON fdc.idPropType=cpt.idPropType
  LEFT JOIN flightvideos fv ON fv.idflight=flights.idflight
  LEFT JOIN FlightProperties fp2 ON flights.idflight=fp2.idflight AND fp2.idproptype=187 WHERE  flights.UserName=?uName GROUP BY flights.idFlight, aircraft.idaircraft

ORDER BY flights.date DESC, dtFlightStart DESC, dtEngineStart DESC, blockOut DESC, hobbsStart DESC, flights.idFlight DESC ---> System.ArgumentNullException: Value cannot be null.
Parameter name: szTelemetry
   at MyFlightbook.Telemetry.TelemetryReference.InitFromTelemetry(String szTelemetry) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1726
   at MyFlightbook.Telemetry.TelemetryReference.Distance() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1952
   at MyFlightbook.Airports.VisitedAirport.<>c__DisplayClass60_0.<DistanceFlownByUser>b__0(LogbookEntry le) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 585
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 189
   --- End of inner exception stack trace ---
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 208
   at MyFlightbook.Airports.VisitedAirport.LookAtAllFlights(FlightQuery fq, LoadTelemetryOption lto, Action`1 action, Boolean fForceLoad) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 547
   at MyFlightbook.Airports.VisitedAirport.DistanceFlownByUser(FlightQuery fq, Boolean fAutofillDistanceFlown, String& error) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 576
   at Member_Airports.btnEstimateDistance_Click(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\Airports.aspx.cs:line 188
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.member_airports_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Occured at: 09/26/2021 13:15:02 (UTC)

Moving to next exception down...

Message
Uncaught exception in ReadRows:
:SELECT flights.idFlight,
    flights.date,
    flights.idaircraft,
    flights.cInstrumentApproaches,
    flights.cLandings,
    flights.crosscountry,
    flights.night,
    flights.IMC,
    flights.simulatedInstrument,
    flights.dualReceived,
    flights.PIC,
    flights.totalFlightTime,
    flights.fHold,
    flights.Route,
    flights.Comments,
    flights.username,
    flights.groundSim,
    flights.fPublic,
    flights.hobbsStart,
    flights.hobbsEnd,
    IF(YEAR(flights.dtEngineStart) < 100, NULL, flights.dtEngineStart) AS dtEngineStart,
    IF(YEAR(flights.dtEngineEnd) < 100, NULL, flights.dtEngineEnd) AS dtEngineEnd,
    IF(YEAR(flights.dtFlightStart) < 100, NULL, flights.dtFlightStart) AS dtFlightStart,
    IF(YEAR(flights.dtFlightEnd) < 100, NULL, flights.dtFlightEnd) AS dtFlightEnd,
    flights.cfi,
    flights.SIC,
    flights.cNightLandings,
    flights.cFullStopLandings,
    flights.idCatClassOverride,
    flights.FlightHash,
    flights.SignatureHash,
    flights.CFIComment,
    flights.SignatureDate,
    flights.CFICertificate,
    flights.CFIExpiration,
    flights.CFIUserName,
    flights.CFIEmail,
    flights.CFIName,
    IF (flights.DigitizedSignature IS NOT NULL AND Length(DigitizedSignature) > 0, 1, 0) AS HasDigitizedSignature,
    flights.SignatureState,
    CAST(UNCOMPRESS(flights.Telemetry) AS CHAR) AS FlightData, 
    IF (coalesce(flights.Telemetry, ft.idflight) IS NULL, 0, 1) AS FlightDataLength,
    ft.distance,
    ft.flightpath,
    ft.telemetrytype,
    fp2.DateValue AS blockOut,
    CONCAT('[', GROUP_CONCAT(DISTINCT IF(fv.idFlightVideos IS NULL, '', JSON_OBJECT("ID", fv.idFlightVideos, "FlightID", fv.idFlight, "VideoReference", fv.vidRef, "Comment", fv.comment)) SEPARATOR ', '), ']') AS FlightVids,
    CONCAT('[', GROUP_CONCAT(DISTINCT IF(fdc.idprop IS NULL, '', JSON_ARRAY(fdc.idprop, fdc.idPropType, ELT(cpt.type + 1, fdc.IntValue, fdc.DecValue, IF(fdc.IntValue<>0, 'true', 'false'), fdc.DateValue, fdc.DateValue, fdc.StringValue, fdc.DecValue))) ORDER BY CONCAT(cpt.sortkey, cpt.FormatString) ASC SEPARATOR ', '), ']') AS CustomPropsJSON,
    GROUP_CONCAT(DISTINCT REPLACE(cpt.FormatString, '{0}', ELT(cpt.type + 1, fdc.IntValue, fdc.DecValue, '', fdc.DateValue, fdc.DateValue, fdc.StringValue, fdc.DecValue)) SEPARATOR ' ') AS CustomProperties,
    models.*,
    IF(models.fTAA <> 0 OR (aircraft.HasTAAUpgrade  <> 0 AND (aircraft.GlassUpgradeDate IS NULL OR flights.date >= aircraft.GlassUpgradeDate)), 1, 0) AS IsTAA,
    if (flights.idCatClassOverride = 0 OR flights.idCatClassOverride=models.idCategoryClass, 0, 1) AS IsOverridden,
    if (flights.idCatClassOverride = 0, models.idcategoryclass, flights.idCatClassOverride) AS CatClassOverride,
    TRIM(CONCAT(models.model, ', ', manufacturers.Manufacturer, ' ',  models.typename, ' ', models.modelname)) AS ModelDisplay,
    TRIM(CONCAT(manufacturers.Manufacturer, ' ', models.model)) AS ShortModelDisplay,
    IF(models.family is null OR models.family='', models.model, models.family) AS FamilyDisplay,
    IF (aircraft.Tailnumber LIKE '#%', CONCAT('(', models.model, ')'), aircraft.tailnumber) AS 'TailNumberDisplay',
    aircraft.TailNumber AS RawTailNumber,
    aircraft.InstanceType,
    CONCAT(IF(ccOver.CatClass is null, ccOrig.CatClass, ccOver.CatClass), IF(models.typename='','', CONCAT(' (', models.typename, ')'))) AS CatClassDisplay FROM flights
  INNER JOIN aircraft ON flights.idaircraft = aircraft.idaircraft
  INNER JOIN models ON aircraft.idmodel = models.idmodel
  INNER JOIN manufacturers ON manufacturers.idmanufacturer = models.idmanufacturer
  INNER JOIN categoryclass ccOrig ON (models.idCategoryClass = ccOrig.idCatClass)
  
  LEFT JOIN flighttelemetry ft ON (flights.idflight=ft.idflight)
  LEFT JOIN categoryclass ccOver ON (flights.idCatClassOverride = ccOver.idCatClass)
  LEFT JOIN FlightProperties fdc ON flights.idFlight=fdc.idFlight
  LEFT JOIN custompropertytypes cpt ON fdc.idPropType=cpt.idPropType
  LEFT JOIN flightvideos fv ON fv.idflight=flights.idflight
  LEFT JOIN FlightProperties fp2 ON flights.idflight=fp2.idflight AND fp2.idproptype=187 WHERE  flights.UserName=?uName GROUP BY flights.idFlight, aircraft.idaircraft

ORDER BY flights.date DESC, dtFlightStart DESC, dtEngineStart DESC, blockOut DESC, hobbsStart DESC, flights.idFlight DESC

Source
MyFlightbook.Web

Target site
Boolean ReadRows(MyFlightbook.DBHelperCommandArgs, System.Action`1[MySql.Data.MySqlClient.MySqlCommand], System.Action`1[MySql.Data.MySqlClient.MySqlDataReader], ReadRowMode)

Stack trace
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 208
   at MyFlightbook.Airports.VisitedAirport.LookAtAllFlights(FlightQuery fq, LoadTelemetryOption lto, Action`1 action, Boolean fForceLoad) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 547
   at MyFlightbook.Airports.VisitedAirport.DistanceFlownByUser(FlightQuery fq, Boolean fAutofillDistanceFlown, String& error) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 576
   at Member_Airports.btnEstimateDistance_Click(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\Airports.aspx.cs:line 188
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Overall Data:
MyFlightbook.MyFlightbookException: Uncaught exception in ReadRows:
:SELECT flights.idFlight,
    flights.date,
    flights.idaircraft,
    flights.cInstrumentApproaches,
    flights.cLandings,
    flights.crosscountry,
    flights.night,
    flights.IMC,
    flights.simulatedInstrument,
    flights.dualReceived,
    flights.PIC,
    flights.totalFlightTime,
    flights.fHold,
    flights.Route,
    flights.Comments,
    flights.username,
    flights.groundSim,
    flights.fPublic,
    flights.hobbsStart,
    flights.hobbsEnd,
    IF(YEAR(flights.dtEngineStart) < 100, NULL, flights.dtEngineStart) AS dtEngineStart,
    IF(YEAR(flights.dtEngineEnd) < 100, NULL, flights.dtEngineEnd) AS dtEngineEnd,
    IF(YEAR(flights.dtFlightStart) < 100, NULL, flights.dtFlightStart) AS dtFlightStart,
    IF(YEAR(flights.dtFlightEnd) < 100, NULL, flights.dtFlightEnd) AS dtFlightEnd,
    flights.cfi,
    flights.SIC,
    flights.cNightLandings,
    flights.cFullStopLandings,
    flights.idCatClassOverride,
    flights.FlightHash,
    flights.SignatureHash,
    flights.CFIComment,
    flights.SignatureDate,
    flights.CFICertificate,
    flights.CFIExpiration,
    flights.CFIUserName,
    flights.CFIEmail,
    flights.CFIName,
    IF (flights.DigitizedSignature IS NOT NULL AND Length(DigitizedSignature) > 0, 1, 0) AS HasDigitizedSignature,
    flights.SignatureState,
    CAST(UNCOMPRESS(flights.Telemetry) AS CHAR) AS FlightData, 
    IF (coalesce(flights.Telemetry, ft.idflight) IS NULL, 0, 1) AS FlightDataLength,
    ft.distance,
    ft.flightpath,
    ft.telemetrytype,
    fp2.DateValue AS blockOut,
    CONCAT('[', GROUP_CONCAT(DISTINCT IF(fv.idFlightVideos IS NULL, '', JSON_OBJECT("ID", fv.idFlightVideos, "FlightID", fv.idFlight, "VideoReference", fv.vidRef, "Comment", fv.comment)) SEPARATOR ', '), ']') AS FlightVids,
    CONCAT('[', GROUP_CONCAT(DISTINCT IF(fdc.idprop IS NULL, '', JSON_ARRAY(fdc.idprop, fdc.idPropType, ELT(cpt.type + 1, fdc.IntValue, fdc.DecValue, IF(fdc.IntValue<>0, 'true', 'false'), fdc.DateValue, fdc.DateValue, fdc.StringValue, fdc.DecValue))) ORDER BY CONCAT(cpt.sortkey, cpt.FormatString) ASC SEPARATOR ', '), ']') AS CustomPropsJSON,
    GROUP_CONCAT(DISTINCT REPLACE(cpt.FormatString, '{0}', ELT(cpt.type + 1, fdc.IntValue, fdc.DecValue, '', fdc.DateValue, fdc.DateValue, fdc.StringValue, fdc.DecValue)) SEPARATOR ' ') AS CustomProperties,
    models.*,
    IF(models.fTAA <> 0 OR (aircraft.HasTAAUpgrade  <> 0 AND (aircraft.GlassUpgradeDate IS NULL OR flights.date >= aircraft.GlassUpgradeDate)), 1, 0) AS IsTAA,
    if (flights.idCatClassOverride = 0 OR flights.idCatClassOverride=models.idCategoryClass, 0, 1) AS IsOverridden,
    if (flights.idCatClassOverride = 0, models.idcategoryclass, flights.idCatClassOverride) AS CatClassOverride,
    TRIM(CONCAT(models.model, ', ', manufacturers.Manufacturer, ' ',  models.typename, ' ', models.modelname)) AS ModelDisplay,
    TRIM(CONCAT(manufacturers.Manufacturer, ' ', models.model)) AS ShortModelDisplay,
    IF(models.family is null OR models.family='', models.model, models.family) AS FamilyDisplay,
    IF (aircraft.Tailnumber LIKE '#%', CONCAT('(', models.model, ')'), aircraft.tailnumber) AS 'TailNumberDisplay',
    aircraft.TailNumber AS RawTailNumber,
    aircraft.InstanceType,
    CONCAT(IF(ccOver.CatClass is null, ccOrig.CatClass, ccOver.CatClass), IF(models.typename='','', CONCAT(' (', models.typename, ')'))) AS CatClassDisplay FROM flights
  INNER JOIN aircraft ON flights.idaircraft = aircraft.idaircraft
  INNER JOIN models ON aircraft.idmodel = models.idmodel
  INNER JOIN manufacturers ON manufacturers.idmanufacturer = models.idmanufacturer
  INNER JOIN categoryclass ccOrig ON (models.idCategoryClass = ccOrig.idCatClass)
  
  LEFT JOIN flighttelemetry ft ON (flights.idflight=ft.idflight)
  LEFT JOIN categoryclass ccOver ON (flights.idCatClassOverride = ccOver.idCatClass)
  LEFT JOIN FlightProperties fdc ON flights.idFlight=fdc.idFlight
  LEFT JOIN custompropertytypes cpt ON fdc.idPropType=cpt.idPropType
  LEFT JOIN flightvideos fv ON fv.idflight=flights.idflight
  LEFT JOIN FlightProperties fp2 ON flights.idflight=fp2.idflight AND fp2.idproptype=187 WHERE  flights.UserName=?uName GROUP BY flights.idFlight, aircraft.idaircraft

ORDER BY flights.date DESC, dtFlightStart DESC, dtEngineStart DESC, blockOut DESC, hobbsStart DESC, flights.idFlight DESC ---> System.ArgumentNullException: Value cannot be null.
Parameter name: szTelemetry
   at MyFlightbook.Telemetry.TelemetryReference.InitFromTelemetry(String szTelemetry) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1726
   at MyFlightbook.Telemetry.TelemetryReference.Distance() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1952
   at MyFlightbook.Airports.VisitedAirport.<>c__DisplayClass60_0.<DistanceFlownByUser>b__0(LogbookEntry le) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 585
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 189
   --- End of inner exception stack trace ---
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 208
   at MyFlightbook.Airports.VisitedAirport.LookAtAllFlights(FlightQuery fq, LoadTelemetryOption lto, Action`1 action, Boolean fForceLoad) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 547
   at MyFlightbook.Airports.VisitedAirport.DistanceFlownByUser(FlightQuery fq, Boolean fAutofillDistanceFlown, String& error) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 576
   at Member_Airports.btnEstimateDistance_Click(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\Airports.aspx.cs:line 188
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Occured at: 09/26/2021 13:15:02 (UTC)

Moving to next exception down...

Message
Value cannot be null.
Parameter name: szTelemetry

Source
MyFlightbook.Web

Target site
Void InitFromTelemetry(System.String)

Stack trace
   at MyFlightbook.Telemetry.TelemetryReference.InitFromTelemetry(String szTelemetry) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1726
   at MyFlightbook.Telemetry.TelemetryReference.Distance() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1952
   at MyFlightbook.Airports.VisitedAirport.<>c__DisplayClass60_0.<DistanceFlownByUser>b__0(LogbookEntry le) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 585
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 189

Overall Data:
System.ArgumentNullException: Value cannot be null.
Parameter name: szTelemetry
   at MyFlightbook.Telemetry.TelemetryReference.InitFromTelemetry(String szTelemetry) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1726
   at MyFlightbook.Telemetry.TelemetryReference.Distance() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\FlightData.cs:line 1952
   at MyFlightbook.Airports.VisitedAirport.<>c__DisplayClass60_0.<DistanceFlownByUser>b__0(LogbookEntry le) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Places\Airports.cs:line 585
   at MyFlightbook.DBHelper.ReadRows(DBHelperCommandArgs args, Action`1 initCommand, Action`1 readRow, ReadRowMode rowMode) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 189

Occured at: 09/26/2021 13:15:02 (UTC)

Moving to next exception down...

**Comment by ericberman** [comment]
Part of the problem with this particular telemetry is that the coordinates have bogus values of -275.
