### ISSUE TITLE
Exception consolidating dupe aircraft

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#867]
mucking in the database gave two aircraft with version 0 but differing by a hyphen in the tail number.  Trying to consolidate gave this:

Stack trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.admin_adminaircraft_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> MyFlightbook.MyFlightbookException: Exception DoNonQuery:
Code = -2147467259
Cannot delete or update a parent row: a foreign key constraint fails (`logbook`.`flights`, CONSTRAINT `fkFlightAircraft` FOREIGN KEY (`idaircraft`) REFERENCES `aircraft` (`idaircraft`) ON UPDATE NO ACTION) DELETE FROM aircraft WHERE idAircraft=?idAircraftOld ---> MySql.Data.MySqlClient.MySqlException: Cannot delete or update a parent row: a foreign key constraint fails (`logbook`.`flights`, CONSTRAINT `fkFlightAircraft` FOREIGN KEY (`idaircraft`) REFERENCES `aircraft` (`idaircraft`) ON UPDATE NO ACTION)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MyFlightbook.DBHelper.DoNonQuery(DBHelperCommandArgs args, Action`1 initCommand) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 270
   --- End of inner exception stack trace ---
   at MyFlightbook.DBHelper.DoNonQuery(DBHelperCommandArgs args, Action`1 initCommand) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\DBHelper.cs:line 278
   at MyFlightbook.AircraftUtility.AdminMergeDupeAircraft(Aircraft acMaster, Aircraft ac) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Aircraft\Aircraft.cs:line 2196
   at MyFlightbook.Web.Admin.AdminAircraft.gvDupeAircraft_RowCommand(Object sender, CommandEventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Admin\AdminAircraft.aspx.cs:line 336
   at System.Web.UI.WebControls.GridView.OnRowCommand(GridViewCommandEventArgs e)
   at System.Web.UI.WebControls.GridView.HandleEvent(EventArgs e, Boolean causesValidation, String validationGroup)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.admin_adminaircraft_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ericberman** [comment]
can't repro. ?

**Comment by ericberman** [comment]
My bad in the repro case.
