### ISSUE TITLE
Some sort of race condition in 8710 form (rollup by time) - modifying enumeration.

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#881]
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
Target site
Boolean HandleError(System.Exception)

Stack trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.member_8710form_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.MemberPages.FAA8710Form.RefreshFormData() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 88
   at MyFlightbook.MemberPages.FAA8710Form.ShowResults(Object sender, FlightQueryEventArgs fqe) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 137
   at System.Web.UI.WebControls.ImageButton.OnClick(ImageClickEventArgs e)
   at System.Web.UI.WebControls.ImageButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()<---
<---

   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.member_8710form_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Occured at: 01/11/2022 16:54:34 (UTC)

Moving to next exception down...

Message: One or more errors occurred.
Source: mscorlib
Target site
Boolean WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)

Stack trace:
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.MemberPages.FAA8710Form.RefreshFormData() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 88
   at MyFlightbook.MemberPages.FAA8710Form.ShowResults(Object sender, FlightQueryEventArgs fqe) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 137
   at System.Web.UI.WebControls.ImageButton.OnClick(ImageClickEventArgs e)
   at System.Web.UI.WebControls.ImageButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()OverallData:
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.MemberPages.FAA8710Form.RefreshFormData() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 88
   at MyFlightbook.MemberPages.FAA8710Form.ShowResults(Object sender, FlightQueryEventArgs fqe) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 137
   at System.Web.UI.WebControls.ImageButton.OnClick(ImageClickEventArgs e)
   at System.Web.UI.WebControls.ImageButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()<---
<---

Occured at: 01/11/2022 16:54:34 (UTC)

Moving to next exception down...

Message: One or more errors occurred.
Source: mscorlib
Target site
Boolean WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)

Stack trace:
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at System.Threading.Tasks.Task.Execute()OverallData:
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()<---

Occured at: 01/11/2022 16:54:34 (UTC)

Moving to next exception down...

Message: Collection was modified; enumeration operation may not execute.
Source: System.Core
Target site
Boolean MoveNext()

Stack trace:
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()OverallData:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MyFlightbook.FlightQuery.UpdateModels(StringBuilder sbQuery) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1080
   at MyFlightbook.FlightQuery.UpdateRestriction() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 1387
   at MyFlightbook.LogbookEntryBase.QueryCommand(FlightQuery fq, Int32 offset, Int32 limit, Boolean fAsc, LoadTelemetryOption lto) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\LogbookEntry.cs:line 1403
   at MyFlightbook.Currency.UserTotals.DataBind() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\Totals.cs:line 971
   at System.Threading.Tasks.Task.Execute()

Occured at: 01/11/2022 16:54:34 (UTC)

Moving to next exception down...

**Comment by ericberman** [comment]
Issue is that DataBind on UserTotals updates the restriction, and this is called from BindTotalsForUser, but possibly while others are modifying the same query.
