### ISSUE TITLE
Periodic exception in Magick

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#901]
Stack trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Magick.Native-Q16-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.Initialize()
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor()
   --- End of inner exception stack trace ---
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor()
   at ImageMagick.MagickSettings..ctor()
   at ImageMagick.MagickImage..ctor()
   at ImageMagick.MagickImage..ctor(Stream stream)
   at MyFlightbook.Image.MFBImageInfo.DrawingCompatibleImageFromStream(Stream s, String& szTemp) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Images\MFBImageInfo.cs:line 1416
   at MyFlightbook.Image.MFBPostedFile.ThumbnailBytes() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Images\MFBPostedFile.cs:line 203
   at Public_PendingImg.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Public\PendingImg.aspx.cs:line 22

**Comment by ericberman** [comment]
Updated Magick, hopefully this will go away.
