### ISSUE TITLE
Still getting rare modification of enumerated object?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#909]
Referrer requested: https://myflightbook.com/logbook/Member/8710Form.aspx?=%40&naked=1
Last page requested by user = https:myflightbook.com/logbook/Member/8710Form.aspx?=@&naked=1

Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
Target site
Boolean HandleError(System.Exception)

Stack trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.member_8710form_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at MyFlightbook.FlightQuery.get_MakeIDList() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 298
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MyFlightbook.util.CopyObject(Object objSrc, Object objDest) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\util.cs:line 269
   at MyFlightbook.FlightQuery..ctor(FlightQuery q) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 736
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.<>c__DisplayClass32_0.<BindTotalsForUser>b__1() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 130
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at MyFlightbook.MemberPages.FAA8710Form.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 60
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at MyFlightbook.FlightQuery.get_MakeIDList() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 298
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MyFlightbook.util.CopyObject(Object objSrc, Object objDest) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\util.cs:line 269
   at MyFlightbook.FlightQuery..ctor(FlightQuery q) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 736
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.<>c__DisplayClass32_0.<BindTotalsForUser>b__1() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 130
   at System.Threading.Tasks.Task.Execute()<---

   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.member_8710form_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Occured at: 02/23/2022 15:29:28 (UTC)

Moving to next exception down...

Message: One or more errors occurred.
Source: mscorlib
Target site
Boolean WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)

Stack trace:
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at MyFlightbook.MemberPages.FAA8710Form.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 60
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()OverallData:
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at MyFlightbook.FlightQuery.get_MakeIDList() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 298
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MyFlightbook.util.CopyObject(Object objSrc, Object objDest) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\util.cs:line 269
   at MyFlightbook.FlightQuery..ctor(FlightQuery q) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 736
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.<>c__DisplayClass32_0.<BindTotalsForUser>b__1() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 130
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.BindTotalsForUser(String szUser, Boolean fLast7Days, Boolean fMonthToDate, Boolean fPreviousMonth, Boolean fPreviousYear, Boolean fYearToDate, FlightQuery fqSupplied) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 137
   at MyFlightbook.MemberPages.FAA8710Form.RefreshTimePeriodRollup() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 67
   at MyFlightbook.MemberPages.FAA8710Form.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\8710Form.aspx.cs:line 60
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at MyFlightbook.FlightQuery.get_MakeIDList() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 298
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MyFlightbook.util.CopyObject(Object objSrc, Object objDest) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Utility\util.cs:line 269
   at MyFlightbook.FlightQuery..ctor(FlightQuery q) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\AppCode\Flights\FlightQuery.cs:line 736
   at MyFlightbook.Currency.mfbTotalsByTimePeriod.<>c__DisplayClass32_0.<BindTotalsForUser>b__1() in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbTotalsByTimePeriod.ascx.cs:line 130
   at System.Threading.Tasks.Task.Execute()<---

**Comment by ericberman** [comment]
Haven't seen this in a while - fixed with something else?
