### ISSUE TITLE
Invalid template ID

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#940]
mr.rogers29

 at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.member_editprofile_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.FormatException: Invalid property template ID ''
   at MyFlightbook.Templates.Controls.Controls_mfbEditPropTemplate.Target(Control c) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbEditPropTemplate.ascx.cs:line 151
   at MyFlightbook.Templates.Controls.Controls_mfbEditPropTemplate.ckDefault_CheckedChanged(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Controls\mfbEditPropTemplate.ascx.cs:line 236
   at System.Web.UI.WebControls.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Web.UI.Page.RaiseChangedEvents()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.member_editprofile_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ericberman** [comment]
Can't reproduce.  Possibly an issue with having two windows open?
