### ISSUE TITLE
invalid time crash in preferences

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#942]
Moving to next exception down...

Message: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive.
Parameter name: time
Source: mscorlib
Target site
Void CheckTicksRange(Int64)

Stack trace:
   at System.Globalization.UmAlQuraCalendar.CheckTicksRange(Int64 ticks)
   at System.Globalization.UmAlQuraCalendar.GetDatePart(DateTime time, Int32 part)
   at System.Globalization.UmAlQuraCalendar.GetDayOfMonth(DateTime time)
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MyFlightbook.MemberPages.Member_EditProfile.InitAccount(tabID sidebarTab) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\EditProfile.aspx.cs:line 219
   at MyFlightbook.MemberPages.Member_EditProfile.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\EditProfile.aspx.cs:line 412
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)OverallData:
System.ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive.
Parameter name: time
   at System.Globalization.UmAlQuraCalendar.CheckTicksRange(Int64 ticks)
   at System.Globalization.UmAlQuraCalendar.GetDatePart(DateTime time, Int32 part)
   at System.Globalization.UmAlQuraCalendar.GetDayOfMonth(DateTime time)
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MyFlightbook.MemberPages.Member_EditProfile.InitAccount(tabID sidebarTab) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\EditProfile.aspx.cs:line 219
   at MyFlightbook.MemberPages.Member_EditProfile.Page_Load(Object sender, EventArgs e) in C:\Users\ericb\Documents\logbook\MyFlightbook.Web\Member\EditProfile.aspx.cs:line 412
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by ericberman** [comment]
No idea how this happened - this is for "last login" and when I look for min/max dates for this, everything is well within range...
