### ISSUE TITLE
Collection was modified -theory?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#975]
Got this more or less at the same time that I was doing a rollup by model in my account.  Is there possibly a static object or something being shared between users?

Request = https://myflightbook.com/logbook/Member/8710Form.aspx/Model
Language=en-AU, en;q=0.5
By: Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Mobile Safari/537.36 1.132.30.130 1.132.30.130

Referrer requested: https://myflightbook.com/logbook/Member/8710Form.aspx/Model
Last page requested by user = https:myflightbook.com/logbook/Member/8710Form.aspx/Model

Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
Target site
Boolean HandleError(System.Exception)

Stack trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.member_8710form_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)OverallData:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

**Comment by ericberman** [comment]
Never mind - same error came by again 20 minutes later.  still don't know what causes this.

**Comment by ericberman** [comment]
Still can't reproduce, and this was only a one-off 2 weeks ago.
